services:
  db:
    image: postgres:16-alpine
    networks:
      - backend
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: petproject
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d petproject"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app/app
      - app_logs:/app/logs
    command: >
      sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --log-file /app/logs/app.log"
    networks:
      - frontend
      - backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/petproject
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  pg_data:
  app_logs:

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
    internal: true  # Нет доступа наружу, только между контейнерами
